name: build
on:
  push:
  workflow_dispatch:

jobs:

  per-arch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64v8
          - arm32v7
          - amd64

    steps:
    - name: Fake build
      run: |
        TIMESTAMP=$(date +%x_%H:%M:%S:%N)
        echo "${{ matrix.arch }}" > /tmp/build.txt
        echo "${{ github.sha }}" >> /tmp/build.txt
        echo $TIMESTAMP >> /tmp/build.txt
        echo "${{ github.sha }}"
        echo $TIMESTAMP
        echo "12345"
    - name: Upload Agent container as artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.arch }}-output
        path: /tmp/build.txt
        
