name: build
on:
  push:
  workflow_dispatch:

jobs:

  per-arch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64v8
          - arm32v7
          - amd64

    steps:
    - name: Fake build
      run: echo "${{ matrix.arch }}" > /tmp/build.txt
    - name: Upload Agent container as artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.arch }}-output
        path: /tmp/build.txt
        
