name: package-fo3

on:
  workflow_run:
    workflows: ["build them all fo3"]
    types: 
      - completed

jobs:
  new-bits:
    runs-on: ubuntu-18.04
    steps:
    - run: |
        echo "HI!"
        printenv
        echo ${{ github.event.workflow_run }}
    
  package-fo3:
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    strategy:
      matrix:
        arch:
          - arm64v8
          - arm32v7
          - amd64
          
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
        commit: ${{ github.event.workflow_run.head_sha }}
        name: build-${{ matrix.arch }}-output
        path: /tmp
    - name: Use build output
      run: |
        echo "Build output: [$(cat /tmp/build.txt)]"
