name: package

on:
  workflow_run:
    workflows: ["build"]
    types: 
      - completed

jobs:
  package:
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    strategy:
      matrix:
        arch:
          - arm64v8
          - arm32v7
          - amd64
          
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token
        ## github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: ${{ github.event.workflow_run.workflow_id }}
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion::
        # "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        # "completed", "in_progress", "queued"
        # Default: "completed"
        workflow_conclusion: success
        # Optional, will get head commit SHA
        ## pr: ${{github.event.pull_request.number}}
        # Optional, no need to specify if PR is
        commit: ${{github.event.pull_request.head.sha}}
        # Optional, will use the branch
        branch: master
        # Optional, will use specified workflow run
        ## run_id: 1122334455
        # Optional, run number from the workflow
        ## run_number: 34
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them in respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        name: build-${{ matrix.arch }}-output
        # Optional, directory where to extract artifact
        path: /tmp/build.txt
        # Optional, defaults to current repo
        ## repo: ${{github.repository}}
    - name: Use build output
      run: |
        echo "Build output: [$(cat /tmp/build.txt)]"
